### ISSUE TITLE
RE with redirect-stdout option

### ISSUE THREAD

**Issue by ionagamed** [xelez/srun2#1]
`sudo ./srun2 --redirect-stdout file ls |& tail --lines=1` leaves an RE for me (`RE 1 0 2066 488 139 Segmentation fault`)

`sudo ./srun2 --redirect-stdin file ls |& tail --lines=1` leaves OK but doesn't work either

**Comment by xelez** [comment]
`sudo` isn't supported at the moment, you have to set SUID bit on the file:

```
chown root ./srun2
chmod u+s ./srun2
```
