### ISSUE TITLE
ML doesn't work

### ISSUE THREAD

**Issue by ionagamed** [xelez/srun2#7]
Running

```
int main() {
    char* ptr = new char[1024 * 1024 * 100];
}
```

with `srun2 --mem 10000 ./main` doesn't give an ML or stuff

**Comment by ionagamed** [comment]
Nevermind, just realised that it's a compiler optimization that reduces the memory

```
int main() {
    char* ptr = new char[1024 * 1024 * 100];
    for (int i = 0; i < 1024 * 1024 * 100; i++) ptr[i] = 1;
}
```

works fine with ML

**Comment by xelez** [comment]
@ionagamed there might be even more strange behaviour, when you declare big array but doesn't fully use it. Then VM (Virtual Memory) is quite big, but RSS(really used) may be less than declared array. It was a long time ago, so I don't remember details.
